// src/lib/components/CommentForm.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import website from '$lib/config/website';
  import { browser } from '$app/env';
  import Card from '$lib/components/Card.svelte';
  import {
    button,
    buttonContainer,
    container,
    content,
    formLink,
    heading,
  } from '$lib/components/CommentForm.css';
  import { EmailInputField, TextArea, TextInputField } from '@rodneylab/sveltekit-components';
  import { FieldError, validEmail } from '$lib/utilities/form';

  export let slug: string;

  const { hcaptchaSitekey, workerUrl } = website;

  let hcaptchaWidgetID: string;
  let hcaptcha;

  const darkMode =
    browser && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

  onMount(() => {
    if (browser) {
      hcaptcha = window.hcaptcha;
      if (hcaptcha.render) {
        hcaptchaWidgetID = hcaptcha.render('hcaptcha', {
          sitekey: hcaptchaSitekey,
          size: 'invisible',
          theme: darkMode ? 'dark' : 'light',
        });
      }
    }
  });

  onDestroy(() => {
    if (browser) {
      hcaptcha = () => {};
    }
  });

  let comment = '';
  let name = '';
  let email = '';

  let errors: { name: FieldError; email: FieldError; comment: FieldError };
  $: errors = { name: null, email: null, comment: null };

  function validateInputs() {
    errors = { ...errors, ...validEmail(email) };
  }

  $: submitting = false;
  $: successfulCommentSubmission = false;

  async function handleSubmit() {
    try {
      validateInputs();
      if (browser) {
        submitting = true;
        const { response } = await hcaptcha.execute(hcaptchaWidgetID, {
          async: true,
        });
        const responsePromise = fetch(`${workerUrl}/post/comment`, {
          method: 'POST',
          credentials: 'omit',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            author: name,
            text: comment,
            email,
            response,
            slug,
          }),
        });
        await responsePromise;
        submitting = false;
        successfulCommentSubmission = true;
      }
    } catch (error) {
      console.error(`Error in CommentForm, handleSubmit: ${error}`);
    }
  }
</script>

<svelte:head>
  <script src="https://js.hcaptcha.com/1/api.js?render=explicit" async defer></script>
</svelte:head>

<Card containerClass={container} contentClass={content}>
  <h2 class={heading}>What's your opinion? Leave a comment.</h2>
  {#if successfulCommentSubmission}
    <div>Thanks for your comment. We will review and post it shortly.</div>
  {:else}
    <form on:submit|preventDefault={handleSubmit}>
      <TextInputField
        value={name}
        id="comment-name"
        placeholder="Blake Costa"
        title="Name"
        error={errors?.email ?? null}
        on:update={(event) => {
          name = event.detail;
        }}
        style="padding-bottom:1.25rem;margin-right:1rem"
      />
      <EmailInputField
        value={email}
        id="contact-email"
        placeholder="blake@example.com"
        title="Email"
        error={errors?.email ?? null}
        on:update={(event) => {
          email = event.detail;
        }}
        style="padding-bottom:1.25rem;margin-right:1rem"
      />
      <TextArea
        value={comment}
        id="contact-message"
        placeholder="Enter your comment here"
        title="Message"
        error={errors?.comment ?? null}
        on:update={(event) => {
          comment = event.detail;
        }}
        style="padding-bottom:1.25rem;margin-right:1rem"
      />
      <small>
        This site uses Akismet to reduce spam.{' '}
        <a
          aria-label="Learn how Akismet process comment data"
          class={formLink}
          href="https://akismet.com/privacy/"
        >
          Learn how your comment data is processed
        </a>
        . We pass your comment, name, email, IP address and{' '}
        <a
          aria-label="Learn more about browser user agent from M D N"
          class={formLink}
          href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent"
        >
          browser user agent
        </a>{' '}
        to Akismet for spam detection. Neither your email address, IP address or user agent is stored
        in our database. This site is protected by
        <a aria-label="Learn more about h Captcha" class={formLink} href="https://www.hCaptcha.com"
          >hCaptcha</a
        >
        and its
        <a
          aria-label="Open h Captcha privacy policy"
          class={formLink}
          href="https://www.hcaptcha.com/privacy">Privacy Policy</a
        >
        and
        <a
          aria-label="Open hCaptcha terms of service"
          class={formLink}
          href="https://www.hcaptcha.com/terms">Terms of Service</a
        > apply.
      </small>
      <div class={buttonContainer}>
        <!-- svelte-ignore component-name-lowercase -->
        <button type="submit" class={button} disabled={submitting}>Leave your comment</button>
      </div>
      <div
        id="hcaptcha"
        class="h-captcha"
        data-sitekey={hcaptchaSitekey}
        data-size="invisible"
        data-theme="dark"
      />
    </form>
  {/if}
</Card>

// demos/narcissus-astro/src/components/CommentForm.tsx
import React, { useState } from 'react';
import type { FC } from 'react';
import {
  button,
  buttonContainer,
  container,
  content,
  formField,
  formLink,
  heading,
} from '$components/CommentForm.css';
import Card from '$components/Card';
import TextInputField from '$components/TextInputField';
import TextArea from '$components/TextArea';
import { ThemeProvider, useTheme } from '$hooks/themeContext';
import website from '$configuration/website';
import { useForm } from 'react-hook-form';

// const ssr = import.meta.env.SSR;
const ssr = typeof window === 'undefined';

interface CommentFormProps {
  slug: string;
}

const { hcaptchaSitekey, workerUrl } = website;

const CommentForm: FC<CommentFormProps> = function CommentForm({ slug }) {
  const [successfulCommentSubmission, setSuccessfulCommentSubmission] = useState<boolean>(false);
  const [submitting, setSubmitting] = useState<boolean>(false);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  let hcaptcha;
  let hcaptchaWidgetID: string;

  const {
    state: { theme },
  } = useTheme();

  function clearForm() {
    ['comment', 'name', 'email'].forEach((element) =>
      sessionStorage.removeItem(`${slug}-${element}`),
    );
    name = '';
    email = '';
    comment = '';
  }

  // function validateInputs() {
  //   errors = { ...errors, ...validName(name), ...validEmail(email), ...validComment(comment) };
  // }

  const onSubmit = async () => {
    try {
      validateInputs();
      if (noErrors() && browser) {
        setSubmitting(true);
        const { response } = await hcaptcha.execute(hcaptchaWidgetID, {
          async: true,
        });
        const responsePromise = fetch(`${workerUrl}/post/comment`, {
          method: 'POST',
          credentials: 'omit',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            author: name,
            text: comment,
            email,
            response,
            slug,
          }),
        });
        await responsePromise;
        setSubmitting(false);
        clearForm();
        setSuccessfulCommentSubmission(true);
      }
    } catch (error) {
      console.error(`Error in CommentForm, handleSubmit: ${error}`);
    }
  };

  return (
    <Card containerClass={container} contentClass={content}>
      <h2 className={heading}>What&apos;s your opinion? Leave a comment.</h2>
      {successfulCommentSubmission ? (
        <div>Thanks for your comment. We will review and post it shortly.</div>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className={formField}>
            <TextInputField
              id="comment-name"
              placeholder="Blake Costa"
              title="Name"
              required
              errors={errors.Name}
              register={register}
              type="text"
            />
          </div>
          <div className={formField}>
            <TextInputField
              id="comment-email"
              placeholder="blake@example.com"
              title="Email"
              required
              errors={errors.Email}
              register={register}
              type="email"
            />
          </div>
          <div className={formField}>
            <TextArea
              id="comment-comment"
              placeholder="Enter your mesage here"
              title="Comment"
              required
              errors={errors.Message}
              register={register}
            />
          </div>
          <small>
            This site uses Akismet to reduce spam.{' '}
            <a
              aria-label="Learn how Akismet process comment data"
              class={formLink}
              href="https://akismet.com/privacy/"
            >
              Learn how your comment data is processed
            </a>
            . We pass your comment, name, email, IP address and{' '}
            <a
              aria-label="Learn more about browser user agent from M D N"
              className={formLink}
              href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent"
            >
              browser user agent
            </a>{' '}
            to Akismet for spam detection. Neither your email address, IP address or user agent is
            stored in our database. This site is protected by
            <a
              aria-label="Learn more about h Captcha"
              className={formLink}
              href="https://www.hCaptcha.com"
            >
              hCaptcha
            </a>
            and its
            <a
              aria-label="Open h Captcha privacy policy"
              className={formLink}
              href="https://www.hcaptcha.com/privacy"
            >
              Privacy Policy
            </a>
            and
            <a
              aria-label="Open hCaptcha terms of service"
              className={formLink}
              href="https://www.hcaptcha.com/terms"
            >
              Terms of Service
            </a>{' '}
            apply.
          </small>
          <div className={buttonContainer}>
            <button type="submit" className={button} disabled={submitting}>
              Leave your comment
            </button>
          </div>
          <div
            id="hcaptcha"
            className="h-captcha"
            data-sitekey={hcaptchaSitekey}
            data-size="invisible"
            data-theme={theme}
          />
        </form>
      )}
    </Card>
  );
};

const ThemeWrapper: FC<{}> = function ThemeWrapper() {
  return (
    <ThemeProvider>
      <CommentForm />
    </ThemeProvider>
  );
};

export default ThemeWrapper;
