// src/lib/components/Footer.svelte
<script>
  import { COPYRIGHT_ENTITY } from '$lib/constants/entities';
  import ExternalLink from '$lib/components/ExternalLink.svelte';
  const { facebookPage, githubPage, linkedinProfile, tiktokUsername, twitterUsername } = website;
  import RodneyLabCredit from '$lib/components/RodneyLabCredit.svelte';
  import TiktokIcon from '$lib/components/Icons/Tiktok.svelte';
  import website from '$lib/config/website';
  import SocialIcons from '@rodneylab/svelte-social-icons';
  import {
    container,
    footerIcons,
    footerIconsList,
    footerIconsListItem,
  } from '$lib/components/Footer.css';
</script>

<footer class={container}>
  <div>
    Created by <a
      aria-label="Open the Rodney Lab site"
      href="https://rodneylab.com/"
      target="_blank"
      rel="noopener noreferrer">Rodney Lab</a
    >. Copyright {COPYRIGHT_ENTITY} 2021.
  </div>
  <nav class={footerIcons}>
    <ul class={footerIconsList}>
      <li class={footerIconsListItem}>
        <ExternalLink
          ariaLabel="Go to the Rodney Lab Tik Tok Page"
          href={`https://www.tiktok.com/${tiktokUsername}`}><TiktokIcon /></ExternalLink
        >
      </li>
      <li class={footerIconsListItem}>
        <ExternalLink ariaLabel="Go to the Rodney Lab Facebook Page" href={facebookPage}
          ><SocialIcons network="facebook" fgColor="#1d3557" bgColor="transparent" /></ExternalLink
        >
      </li>
      <li class={footerIconsListItem}>
        <ExternalLink
          ariaLabel="Go to the Rodney Lab Twitter Page"
          href={`https://twitter.com/intent/user?screen_name=${twitterUsername}`}
          ><SocialIcons network="twitter" fgColor="#1d3557" bgColor="transparent" /></ExternalLink
        >
      </li>
      <li class={footerIconsListItem}>
        <ExternalLink
          ariaLabel="Go to the Rodney Lab Linked In Page"
          href={`https://uk.linkedin.com/in/${linkedinProfile}`}
          ><SocialIcons network="linkedin" fgColor="#1d3557" bgColor="transparent" /></ExternalLink
        >
      </li>
      <li class={footerIconsListItem}>
        <ExternalLink
          ariaLabel="Go to the Rodney Lab Git Hub In Page"
          href={`https://github.com/${githubPage}`}
          ><SocialIcons network="github" fgColor="#1d3557" bgColor="transparent" /></ExternalLink
        >
      </li>
    </ul>
  </nav>
  <RodneyLabCredit />
</footer>

// demos/narcissus-astro/src/components/Layout/Footer.tsx
import React from 'react';
import type { FC } from 'react';
import website from '../../configuration/website';

import { COPYRIGHT_ENTITY } from '../../constants/entities';
import ExternalLink from '../ExternalLink';
import SocialIcons from '../SocialIcons';
import {
  container,
  content,
  copyrightText,
  footerIcons,
  footerIconsList,
  footerIconsListItem,
  footerLink,
} from './Footer.css';
import RodneyLabCredit from './RodneyLabCredit';

const Footer: FC<{}> = () => {
  const { facebookPage, githubPage, linkedinProfile, tiktokUsername, twitterUsername } = website;
  const theme: string = 'dark';
  const fgColor = theme === 'light' ? '#433633' : '#32021f';
  return (
    <footer className={container}>
      <div className={content}>
        <div className={copyrightText}>
          {' '}
          Created by{' '}
          <a
            aria-label="Open the Rodney Lab site"
            className={footerLink}
            href="https://rodneylab.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Rodney Lab
          </a>
          . Copyright {COPYRIGHT_ENTITY} 2021.
        </div>
        <nav className={footerIcons} aria-label="Navigate to Rodney Lab linked social sites">
          <ul className={footerIconsList}>
            <li className={footerIconsListItem}>
              <ExternalLink
                aria-label="Go to the Rodney Lab Tik Tok Page"
                href={`https://www.tiktok.com/${tiktokUsername}`}
              >
                <SocialIcons network="tiktok" fgColor="transparent" bgColor={fgColor} />
              </ExternalLink>
            </li>
            <li className={footerIconsListItem}>
              <SocialIcons
                url={facebookPage}
                network="facebook"
                fgColor={fgColor}
                bgColor="transparent"
              />
            </li>
            <li className={footerIconsListItem}>
              <SocialIcons
                url={`https://twitter.com/intent/user?screen_name=${twitterUsername}`}
                network="twitter"
                fgColor={fgColor}
                bgColor="transparent"
              />
            </li>
            <li className={footerIconsListItem}>
              <SocialIcons
                url={`https://uk.linkedin.com/in/${linkedinProfile}`}
                network="linkedin"
                fgColor={fgColor}
                bgColor="transparent"
              />
            </li>
            <li className={footerIconsListItem}>
              <SocialIcons
                url={`https://github.com/${githubPage}`}
                network="github"
                fgColor={fgColor}
                bgColor="transparent"
              />
            </li>
          </ul>
        </nav>
        <RodneyLabCredit />
      </div>
    </footer>
  );
};

export { Footer as default };
