// src/components/Card.tsx
import type { ReactNode } from 'react';
import { container, content } from './Card.css';
import React from 'react';

const Card = ({
  children,
  containerClass,
  contentClass,
}: {
  children: ReactNode;
  containerClass: string;
  contentClass: string;
}) => (
  <section className={`${container} ${containerClass ?? ''}`}>
    <div className={`${content} ${contentClass ?? ''}`}>{children}</div>
  </section>
);
export { Card as default };

// demos/narcissus-sveltekit/src/lib/components/Card.svelte
<script lang="ts">
  export let containerClass: string = undefined;
  export let contentClass: string = undefined;
  import { container, content } from '$lib/components/Card.css';
</script>

<section class={`${container} ${containerClass ?? ''}`}>
  <div class={`${content} ${contentClass ?? ''}`}>
    <slot />
  </div>
</section>
