// demos/narcissus-astro/src/components/Card.tsx
import React from 'react';
import type { FC } from 'react';
import { container, content } from '$components/Card.css';

interface CardProps {
  containerClass?: string;
  contentClass?: string;
}

const Card: FC<CardProps> = function Card({ children, containerClass, contentClass }) {
  return (
    <section className={`${container} ${containerClass ?? ''}`}>
      <div className={`${content} ${contentClass ?? ''}`}>{children}</div>
    </section>
  );
};

Card.defaultProps = {
  containerClass: '',
  contentClass: '',
};

export default Card;

// demos/narcissus-sveltekit/src/lib/components/Card.svelte
<script lang="ts">
  export let containerClass: string = undefined;
  export let contentClass: string = undefined;
  import { container, content } from '$lib/components/Card.css';
</script>

<section class={`${container} ${containerClass ?? ''}`}>
  <div class={`${content} ${contentClass ?? ''}`}>
    <slot />
  </div>
</section>
