// demos/narcissus-astro/src/components/BannerImage.tsx
import { container } from '$components/BannerImage.css';
import type { JSX } from 'react';
import { useEffect } from 'react';
import lazyload from 'vanilla-lazyload';

interface BannerImageProps {
  imageData: {
    alt: string;
    width: number;
    height: number;
    src: string;
    sources: { srcset: string; type: string }[];
    placeholder: string;
  };
}

const BannerImage = function BannerImage({ imageData }: BannerImageProps): JSX.Element {
  const { alt, width, height, src, sources, placeholder } = imageData;
  const sizes = '(max-width: 672px) calc(100vw - 32px), 672px';
  const ssr = import.meta.env.SSR;

  useEffect(() => {
    if (!ssr && !window.document.lazyloadInstance) {
      window.document.lazyloadInstance = new lazyload();
    }
  }, [ssr]);

  useEffect(() => {
    if (!ssr) {
      document.lazyloadInstance.update();
    }
  }, [placeholder, sources, src, ssr]);

  return (
    <div>
      <picture>
        {sources.map((element) => {
          const { srcset, type } = element;
          return (
            <source
              data-sizes={sizes}
              data-srcset={srcset}
              key={type}
              type={type}
              width={width}
              height={height}
            />
          );
        })}
        <img
          className={`${container} lazy`}
          alt={alt}
          importance="high"
          loading="eager"
          decoding="async"
          width={width}
          height={height}
          data-src={src}
          src={placeholder}
          objectfit="contain"
        />
      </picture>
    </div>
  );
};

export default BannerImage;

// src/lib/components/BannerImage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/env';
  import { Image } from '@rodneylab/sveltekit-components';

  export let imageData;

  onMount(() => {
    if (browser) {
      document.lazyloadInstance.update();
    }
  });

  const { alt, width, height, src, sources, placeholder } = imageData;
  const sizes = '(max-width: 672px) calc(100vw - 32px), 672px';
</script>

<!-- <picture>
  {#each sources as { srcset, type }}
    <source data-sizes={sizes} data-srcset={srcset} {type} {width} {height} />
  {/each}
  <img
    class="lazy"
    {alt}
    loading="eager"
    decoding="async"
    data-src={src}
    src={placeholder}
    {width}
    {height}
  />
</picture> -->

<Image
  {alt}
  {width}
  loading="eager"
  {height}
  {src}
  {sources}
  {placeholder}
  {sizes}
  style={'border-radius:12px;margin-bottom:48px'}
/>

<!-- <style lang="scss">
  img {
    border-radius: $spacing-3;
    background-size: cover;
    background-color: $color-theme-4;
    margin-bottom: $spacing-12;
  }
</style> -->
