// demos/narcissus-astro/src/components/Layout/Header.tsx
import React, { useContext } from 'react';
import type { FC } from 'react';
import { screenReaderText } from '../../styles/styles.css';
import { themeButton, themeButtonContainer } from './Header.css.ts';
import MoonIcon from '../Icons/Moon';
import SunIcon from '../Icons/Sun';
import {
  container,
  content,
  nav,
  navLink,
  navLinkActive,
  navList,
  navListItem,
  themeIcon,
} from './Header.css';
import { useTheme } from '../../hooks/themeContext';

function Header({ slug }: { slug: string }) {
  const {
    state: { theme },
  } = useTheme();
  const lightThemeActive = theme === 'light';
  const themeButtonText = `Switch to ${lightThemeActive ? 'dark' : 'light'} theme`;

  const { dispatch } = useTheme();

  return (
    <header className={container}>
      <div className={themeButtonContainer}>
        <button type="button" className={themeButton} onClick={() => dispatch()}>
          <span className={screenReaderText}>{themeButtonText}</span>
          <div className={themeIcon}>{lightThemeActive ? <MoonIcon /> : <SunIcon />}</div>
        </button>
      </div>
      <div className={content}>
        <nav className={nav} aria-label="Site navigation">
          <ul className={navList}>
            <li className={navListItem}>
              <a className={`${navLink}${slug === '/' ? ` ${navLinkActive}` : ''}`} href="/.">
                Home
              </a>
            </li>
            <li className={navListItem}>
              <a
                className={`${navLink}${slug === '/contact' ? ` ${navLinkActive}` : ''}`}
                href="/contact"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
}

export { Header as default };

// src/lib/components/Layout/Header.svelte
<script lang="ts">
  import SunIcon from '$lib/components/Icons/Sun.svelte';
  import MoonIcon from '$lib/components/Icons/Moon.svelte';
  import theme from '$lib/shared/stores/theme';
  import {
    container,
    content,
    nav,
    navLink,
    navLinkActive,
    navList,
    navListItem,
    themeButton,
    themeButtonContainer,
  } from './Header.css';
  $: lightThemeActive = $theme === 'light';
  $: themeButtonText = `Switch to ${lightThemeActive ? 'dark' : 'light'} theme`;
  import { screenReaderText } from '$lib/styles/styles.css';

  export let slug: string;
</script>

<header class={container}>
  <div class={themeButtonContainer}>
    <button
      class={themeButton}
      on:click={() => {
        lightThemeActive ? theme.set('dark') : theme.set('light');
      }}
      ><span class={screenReaderText}>{themeButtonText}</span>
      {#if lightThemeActive}
        <MoonIcon label="Switch to dark mode" scale={1.5} />
      {:else}
        <SunIcon label="Switch to light mode" scale={1.5} />
      {/if}</button
    >
  </div>
  <div class={content}>
    <!-- svelte-ignore component-name-lowercase -->
    <nav class={nav} aria-label="Site navigation">
      <ul class={navList}>
        <li class={navListItem}>
          <a class={`${navLink}${slug === '/' ? ` ${navLinkActive}` : ''}`} href="/.">Home</a>
        </li>
        <li class={navListItem}>
          <a class={`${navLink}${slug === '/contact' ? ` ${navLinkActive}` : ''}`} href="/contact"
            >Contact</a
          >
        </li>
      </ul>
    </nav>
  </div>
</header>
