// demos/narcissus-astro/src/components/Layout/RodneyLabCredit.tsx
import React from 'react';
import type { FC } from 'react';
import { container, link, logo, rodneyLabText } from '$components/Layout/RodneyLabCredit.css';

const RodneyLabCredit: FC<{}> = () => (
  <div className={container}>
    A project by{' '}
    <a
      aria-label="Open the Rodney Lab site"
      href="https://rodneylab.com/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <img
        alt="Rodney Lab Logo"
        className={logo}
        src="/assets/rodneylab-logo.png"
        height="16"
        width="16"
      />
    </a>
    <a
      aria-label="Open the Rodney Lab site"
      className={link}
      href="https://rodneylab.com/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <span className={rodneyLabText}>RODNEY LAB</span>
    </a>
    .
  </div>
);

export { RodneyLabCredit as default };

// src/lib/components/Layout/RodneyLabCredit.svelte
<script>
  import '@fontsource/lato/300.css';
  import '@fontsource/lato/400.css';
  import { container, logo, rodneyLabText } from '$lib/components/Layout/RodneyLabCredit.css';
</script>

<div class={container}>
  A project by <a
    aria-label="Open the Rodney Lab site"
    href="https://rodneylab.com/"
    target="_blank"
    rel="noopener noreferrer"
    ><img
      alt="Rodney Lab Logo"
      class={logo}
      src="/assets/rodneylab-logo.png"
      height="16"
      width="16"
    /></a
  >
  <a
    aria-label="Open the Rodney Lab site"
    href="https://rodneylab.com/"
    target="_blank"
    rel="noopener noreferrer"><span class={rodneyLabText}>RODNEY LAB</span></a
  >.
</div>
